### ISSUE TITLE
can you please provide docker image support arm64 platform?[FEATURE]

### ISSUE THREAD

**Issue by lazyzyf** [tobybatch/kimai2#483] opened 2023-03-03 15:43 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tobybatch** [comment] 2023-03-21 07:32
This is a duplicate of #466

**Closed as completed by tobybatch** 2023-03-21 07:32 UTC
