### ISSUE TITLE
[BUG] Doctrine DBAL - Invalid platform version

### ISSUE THREAD

**Issue by SaturnusDJ** [tobybatch/kimai2#540] opened 2023-08-29 11:57 UTC
Been using this build script for a while:
```
#!/bin/bash
wget https://github.com/tobybatch/kimai2/archive/refs/heads/main.zip -O /root/kimai-docker.zip
7z x -o/root/ /root/kimai-docker.zip
mv /root/kimai2-main /root/kimai-docker/
rm /root/kimai-docker.zip
docker build --rm --no-cache -f /root/kimai-docker/Dockerfile -t kimai:$1 --build-arg BASE=apache --build-arg KIMAI=$1 /root/kimai-docker/
rm -r /root/kimai-docker/
docker image prune -f
```
E.g. `./build-kimai.sh 2.0.29`

Since Kimai 2.0.30 this error:
```
request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception: "Invalid platform version "" specified. The platform version has to be specified in the format: "<major_version>.<minor_version>.<patch_version>"." at /opt/kimai/vendor/doctrine/dbal/src/Exception.php line 54 {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0): Invalid platform version \"\" specified. The platform version has to be specified in the format: \"<major_version>.<minor_version>.<patch_version>\". at /opt/kimai/vendor/doctrine/dbal/src/Exception.php:54)"} []

request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception: Invalid platform version "" specified. The platform version has to be specified in the format: "<major_version>.<minor_version>.<patch_version>". at /opt/kimai/vendor/doctrine/dbal/src/Exception.php line 54) {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0): Invalid platform version \"\" specified. The platform version has to be specified in the format: \"<major_version>.<minor_version>.<patch_version>\". at /opt/kimai/vendor/doctrine/dbal/src/Exception.php:54)"} []

php.CRITICAL: Uncaught Exception: Invalid platform version "" specified. The platform version has to be specified in the format: "<major_version>.<minor_version>.<patch_version>". {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0): Invalid platform version \"\" specified. The platform version has to be specified in the format: \"<major_version>.<minor_version>.<patch_version>\". at /opt/kimai/vendor/doctrine/dbal/src/Exception.php:54)\n[previous exception] [object] (Doctrine\\DBAL\\Exception(code: 0): Invalid platform version \"\" specified. The platform version has to be specified in the format: \"<major_version>.<minor_version>.<patch_version>\". at /opt/kimai/vendor/doctrine/dbal/src/Exception.php:54)"} []

request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception: "Invalid platform version "" specified. The platform version has to be specified in the format: "<major_version>.<minor_version>.<patch_version>"." at /opt/kimai/vendor/doctrine/dbal/src/Exception.php line 54 {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0): Invalid platform version \"\" specified. The platform version has to be specified in the format: \"<major_version>.<minor_version>.<patch_version>\". at /opt/kimai/vendor/doctrine/dbal/src/Exception.php:54)\n[previous exception] [object] (Doctrine\\DBAL\\Exception(code: 0): Invalid platform version \"\" specified. The platform version has to be specified in the format: \"<major_version>.<minor_version>.<patch_version>\". at /opt/kimai/vendor/doctrine/dbal/src/Exception.php:54)"} []

```

Server: Redacted
Docker version:
```
Redacted
```

No Docker compose

Run Kimai:
```
docker run -d --restart=unless-stopped \
  --name kimai-mariadb_TEST \
  --net=main --ip=X \
  -e MARIADB_DATABASE=kimai \
  -e MARIADB_USER=kimai \
  -e MARIADB_PASSWORD=Test1234 \
  -e MARIADB_ROOT_PASSWORD=Test4567 \
mariadb:10.11.2

docker run -d  --restart=unless-stopped \
  --name kimai_TEST \
  --net=main --ip=X \
  -p 8011:8001 \
  -e DATABASE_URL=mysql://kimai:Test1234@X:3306/kimai \
  -e memory_limit=536870912 \
kimai:2.0.30
```

**Comment by kevinpapst** [comment] 2023-08-29 11:59
Duplicate of #531

**Closed as completed by kevinpapst** 2023-08-29 11:59 UTC
Labels: duplicate
