### ISSUE TITLE
[BUG] The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by sgaechter** [tobybatch/kimai2#149] opened 2020-09-03 13:20 UTC
**Describe the bug**
After booting the Container, The server returned a "500 Internal Server Error". when calling Kimai in Browser.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container 'docker run --rm -ti -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-1.8-dev'
2. call 'http://host:8001'
4. See error "500 Internal Server Error"

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker version: 19.03.12, build 48a66213fe
 - Docker compose version: 1.26.2

**Command used to run the container**
 - 'docker run --rm -ti -p 8001:8001 --name kimai2 kimai/kimai2:apache-debian-1.8-dev'

**Additional Infos:
I also tried other Container versions like "apache-debian-1.8-prod", apache-debian-1.9-prod and dev - same Issue. Maybe the problem lay's on Kimai itself?
[docker.log](https://github.com/tobybatch/kimai2/files/5168905/docker.log)

**Comment by kevinpapst** [comment] 2020-09-03 13:28
why do you use 1.8 if there are newer versions available?

**Comment by sgaechter** [comment] 2020-09-03 13:39
Because this is mentioned on Docker hub to get a running Kimai-Evaluate: https://hub.docker.com/r/kimai/kimai2

**Comment by tobybatch** [comment] 2020-09-03 14:19
Can you try http://localhost:8001/en/login as that same command works for me.

**Comment by tobybatch** [comment] 2020-09-03 14:25
This is (I think) caused by the trusted hosts setting that defaults to contain localhost but not your.host.name

The section under **Runtime Arguments** explains how to set those values based on the kimai install instructions.

**Comment by sgaechter** [comment] 2020-09-03 18:32
Still no luck.
I rebuilded the  Container either with 1.9-prod, and 1.9-dev, the following causes after Run:

 Rebuilding your cache, please be patient ...
 // Clearing the cache for the prod environment with debug false
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

 // Warming up the cache for the prod environment with debug false

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.

 [OK] Congratulations! Successfully installed Kimai 2 version 1.9 (stable)

Kimai2 ready

Reloading configurations ...
============================
 **[ERROR] File or directory "config" is not readable.**

[Thu Sep 03 19:29:53.896909 2020] [mpm_prefork:notice] [pid 27] AH00163: Apache/2.4.38 (Debian) PHP/7.4.9 configured -- resuming normal operations
[Thu Sep 03 19:29:53.897051 2020] [core:notice] [pid 27] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'


by calling HTTP://localhost:8006/login/en/ The following stack trace is shown:
TypeError:
Argument 1 passed to Twig\Environment::getTemplateClass() must be of the type string, null given, called in /opt/kimai/vendor/twig/twig/src/Environment.php on line 309

  at /opt/kimai/vendor/twig/twig/src/Environment.php:259
  at Twig\Environment->getTemplateClass(null)
     (/opt/kimai/vendor/twig/twig/src/Environment.php:309)
  at Twig\Environment->load(null)
     (/opt/kimai/vendor/twig/twig/src/Environment.php:277)
  at Twig\Environment->render(null, array('raw_exception' => object(TypeError), 'exception' => object(FlattenException), 'status' => 'error', 'status_code' => 500, 'status_text' => 'Internal Server Error', 'currentContent' => '', 'logger' => object(Logger)))
     (/opt/kimai/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php:378)
  at FOS\RestBundle\View\ViewHandler->renderTemplate(object(View), 'html')
     (/opt/kimai/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php:457)
  at FOS\RestBundle\View\ViewHandler->initResponse(object(View), 'html')
     (/opt/kimai/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php:431)
  at FOS\RestBundle\View\ViewHandler->createResponse(object(View), object(Request), 'html')
     (/opt/kimai/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php:315)
  at FOS\RestBundle\View\ViewHandler->handle(object(View))
     (/opt/kimai/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php:82)
  at FOS\RestBundle\Controller\ExceptionController->showAction(object(Request), object(TypeError), object(Logger))
     (/opt/kimai/vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 2)
     (/opt/kimai/vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 2, false)
     (/opt/kimai/vendor/symfony/http-kernel/EventListener/ErrorListener.php:60)
  at Symfony\Component\HttpKernel\EventListener\ErrorListener->onKernelException(object(ExceptionEvent))
     (/opt/kimai/vendor/friendsofsymfony/rest-bundle/EventListener/ExceptionListener.php:80)
  at FOS\RestBundle\EventListener\ExceptionListener->onKernelException(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (/opt/kimai/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:126)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (/opt/kimai/vendor/symfony/event-dispatcher/EventDispatcher.php:264)
  at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(ExceptionEvent))
     (/opt/kimai/vendor/symfony/event-dispatcher/EventDispatcher.php:239)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(ExceptionEvent))
     (/opt/kimai/vendor/symfony/event-dispatcher/EventDispatcher.php:73)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (/opt/kimai/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:168)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (/opt/kimai/vendor/symfony/http-kernel/HttpKernel.php:219)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable(object(TypeError), object(Request), 1)
     (/opt/kimai/vendor/symfony/http-kernel/HttpKernel.php:112)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException(object(TypeError), object(Request))
     (/opt/kimai/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:119)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}(object(TypeError))
     (/opt/kimai/vendor/symfony/error-handler/ErrorHandler.php:599)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException(object(TypeError))

**Comment by tobybatch** [comment] 2020-09-04 07:39
Can you paste in the command you are using to start the container please.

**Comment by TheFehr** [comment] 2020-09-17 09:01
I seem to have the exact same error

**Comment by tobybatch** [comment] 2020-09-17 18:33
@TheFehr Can you paste in the command you are using to start the container please.

**Comment by TheFehr** [comment] 2020-09-17 18:38
I fixed it by setting proper TRUSTED_HOSTS env variable. 
I just can't yet understand why the logs says something about no access to "config" and it's fixed by that env var.

**Comment by tobybatch** [comment] 2020-09-18 08:01
TRUSTED_HOSTS is the single most common cause of issues with the FPM set up.

The config error a known bug in the kimai command.  Kevin is looking at it, we know the cause and it's just a red herring.  If you call ```kimai:reload``` from a folder other than the root of the site it doesn't find the config folder.

There's a PR open to fix it and we'll probably get it in the next release or so but it can safely be ignored.

**Closed as completed by tobybatch** 2020-09-18 08:01 UTC
